# Etapa de construcción y pruebas del microservicio
FROM maven:latest as builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/main ./src/main
COPY src/test ./src/test
RUN mvn test

# Etapa de construcción y ejecución del microservicio
FROM maven:latest
WORKDIR /app
COPY --from=builder /app /app
RUN mvn package

EXPOSE 8080
CMD ["java", "-jar", "target/microservice.jar"]
